export enum Subjects {
  NEW_USER_REGISTERED = "NEW_USER_REGISTERED",
  REMOVE_ISTEYIM_USER = "REMOVE_ISTEYIM_USER",
  BACKOFFICE_USER_CREATED = "BACKOFFICE_USER_CREATED",
  NEW_COMPANY_REGISTERED = "NEW_COMPANY_REGISTERED",
  COMPANY_INFO_UPDATED = "COMPANY_INFO_UPDATED",
  USER_INFORMATION_STATUS_CHANGED = "USER_INFORMATION_STATUS_CHANGED",
  RESUME_STATUS_CHANGED = "RESUME_STATUS_CHANGED",
  COMPANY_INFO_STATUS_CHANGED = "COMPANY_INFO_STATUS_CHANGED",
  COMPANY_INFO_COMPLETED = "COMPANY_INFO_COMPLETED",
  COMPANY_INFO_REVIEW_COMPLETED = "COMPANY_INFO_REVIEW_COMPLETED",
}
