export enum FileType {
  CRIMINAL_RECORD = "CRIMINAL_RECORD",
  HIGH_SCHOOL_DIPLOMA = "HIGH_SCHOOL_DIPLOMA",
  ASSOCIATE_DIPLOMA = "ASSOCIATE_DIPLOMA",
  BACHELOR_DIPLOMA = "BACHELOR_DIPLOMA",
  MASTER_DIPLOMA = "MASTER_DIPLOMA",
  PHD_DIPLOMA = "PHD_DIPLOMA",
  CERTIFICATION = "CERTIFICATION",
}
