export enum UserRole {
    ROLE_ISTEYIM_LEVEL_1 = "ROLE_ISTEYIM_LEVEL_1",
    ROLE_ISTEYIM_LEVEL_2 = "ROLE_ISTEYIM_LEVEL_2",
    ROLE_ADMIN = "ROLE_ADMIN",
    ROLE_BACKOFFICE = "ROLE_BACKOFFICE",
    ROLE_INMIDI_BACKOFFICE_ADMIN = "ROLE_INMIDI_BACKOFFICE_ADMIN",
}